### ISSUE TITLE
Zeitliche Sperre für mehrmaliges Eingeben des falschen Passworts

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#14]

**Comment by maxxxor** [comment]
Warum? 🤔

**Comment by BenjiGat** [comment]
Um zu verhindern, das irgendwelche Bots versuchen sich anzumelden. Ist Ansichtssache.

**Comment by maxxxor** [comment]
Ah. Verstehe. Ein Client ist für etwas "nicht sicher" genug. Das wird in der API geregelt.
