### ISSUE TITLE
Tabbar Icons zu klein (iOS)

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#2]
"Icons etwas größer/fetter"

**Comment by maxxxor** [comment]
Welche? Hauptmenü? Equipment? Account? Alle? 🤔

**Comment by BenjiGat** [comment]
Die Icons im Menü unten sollten etwa so groß sein, wie die Icons neben den Überschriften der screens.

![CCCC35ED-33A2-4CEF-87BA-953BE29185ED_1_201_a](https://github.com/user-attachments/assets/fcf09b9c-678b-4fec-97b2-652c1e62cd98)

**Comment by maxxxor** [comment]
Ah! Danke für den Screenshot. Habe die ein wenig größer gemacht.
