### ISSUE TITLE
Login -> Speicher-Button ist immer klickbar

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#20]

**Comment by maxxxor** [comment]
Was genau meinst du damit? Wenn der Name z.B. leer ist, ist der Button nicht mehr klickbar.

**Comment by BenjiGat** [comment]
Der Button sollte mMn nur auftauchen, wenn etwas (Benutzername) geändert wurde.

**Comment by maxxxor** [comment]
Nachvollziehbar. Ich würde das mal für die Zukunft in Betracht ziehen. Ist derzeit ein unnötiger Aufwand.
