### ISSUE TITLE
Emojis in Eingabefeldern möglich

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#3]
"Emojis in Textfeldern möglich"

**Comment by maxxxor** [comment]
Würdest du das grundsätzlich unterbinden und warum?

**Comment by BenjiGat** [comment]
Für Namen oder Gerätebezeichnungen ist es in Ordnung. Für Logindaten sollte es mMn ausgeschlossen werden, um möglihe Eingabefehler zu vermeiden.

**Comment by maxxxor** [comment]
Verstehe. Ich bin kein großer Fan von Eingabe-Einschränkungen. Außer es geht um Sicherheit. Sollen die doch eingeben was Sie wollen. Bei der Anmeldung / Registrierung würdest du so z.B. die Besitzer der Emoji-Domains ausschließen. Die damalige Einführung der neuen TLDs hat uns gelehrt, dass wir das nicht bei der Eingabe, sondern eher über eine Bestätigungsmail einschränken sollten :)
