### ISSUE TITLE
Meldung per Telefon

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#39]

**Comment by maxxxor** [comment]
Was genau meinst du damit? Startet ein Anruf? Wird in der Meldung hinterlegt, dass ich die Meldung per Telefon gemacht habe?

**Comment by BenjiGat** [comment]
Auswahlmoglichkeit, ob der User die Meldung nur per Mail versenden will, oder anrufen möchte. Falls der Servicebetrieb nur Anrufe annimmt, oder mit der E-Mail ein Problem hat.
