### ISSUE TITLE
Fehlermeldungen (Darstellung anpassen, Text auf deutsch)

### ISSUE THREAD

**Issue by maxxxor** [maxxxor/codees-app-public#44]

**Comment by BenjiGat** [comment]
z.B. im Login screen, wenn der User falsche Daten angibt: Texte auf deutsch und das Feld vielleicht mit nem orangen Rahmen oder so, damit es auffällt.

![2D75A41B-283E-4910-93B2-C1E8487F7DFC_1_201_a](https://github.com/user-attachments/assets/f4d70ffe-cc86-479d-9977-bf1745172d19)
