### ISSUE TITLE
Keine Daten gefunden (Menü Verlauf)

### ISSUE THREAD

**Issue by BenjiGat** [maxxxor/codees-app-public#45]
Geräte werden nach dem Erstellen im Verlauf angezeigt, beim Öffnen kommt die Fehlermeldung "Keine Daten gefunden" (siehe screenshot)

Der Fehler tritt auf, wenn bei der Geräteerstellung das Foto erst im Nachhinein (über Bearbeiten) hinzugefügt wird. Das Gerät lässt sich ohne Foto problemlos öffnen. Sobald das Gerät im Menü "codees" oder "Favoriten" geöffnet wurde, funktioniert es auch im Menü "Verlauf".

![57BBD6E1-D0E4-43BB-858E-578FC163D657_1_102_o](https://github.com/user-attachments/assets/1558c141-0e7a-4390-8270-5cc9815e2128)

**Comment by maxxxor** [comment]
Super! Danke! Der war wichtig! 👍🏻
